version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    ports: 
     - 3306:3306
    container_name: materialbestellung-mysqldb
    environment:
     - MYSQL_ROOT_PASSWORD=Master01
     - MYSQL_DATABASE=materialbestellung
    volumes:
     - /tmp/matTest/db/:/var/lib/mysql
    restart: always
  appliaktion:
    image: timoheld/materialbestellung:v1.0
    ports:
      - 5001:5000
    container_name: materialbestellung-app
    environment:
     - DATABASE_URL=mysql+pymysql://root:Master01@materialbestellung-mysqldb:3306/materialbestellung
    volumes:
      - /tmp/matArsch/materialbestellung/:/materialbestellung
    restart: always
    depends_on:
      - mysqldb
