version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    ports: 
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=Master01
     - MYSQL_DATABASE=materialbestellung
    volumes:
     - /root/materialbestellung/db/:/var/lib/mysql
    restart: always
  appliaktion:
    #image: materialbestellung:v0.3
    image: gunicorn:v0.1
    ports:
      - 5000:5000
    volumes:
      - /root/materialbestellung/:/materialbestellung
    restart: always
    depends_on:
      - mysqldb
