"""empty message

Revision ID: 0b1f665c5991
Revises: f937e108fb00
Create Date: 2023-03-20 16:12:19.656151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b1f665c5991'
down_revision = 'f937e108fb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bestellung', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('bestellung_ibfk_1', 'bestellung', type_='foreignkey')
    op.create_foreign_key(None, 'bestellung', 'user', ['user_id'], ['id'])
    op.drop_column('bestellung', 'scoutname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bestellung', sa.Column('scoutname', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bestellung', type_='foreignkey')
    op.create_foreign_key('bestellung_ibfk_1', 'bestellung', 'user', ['scoutname'], ['id'])
    op.drop_column('bestellung', 'user_id')
    # ### end Alembic commands ###
