"""empty message

Revision ID: 5ef9a24e4927
Revises: 7469ba3bc2aa
Create Date: 2023-03-21 16:42:03.246759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ef9a24e4927'
down_revision = '7469ba3bc2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expiration', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
