"""empty message

Revision ID: 6c29c54ce4c1
Revises: 5126f7a9753c
Create Date: 2023-03-15 22:12:22.283540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c29c54ce4c1'
down_revision = '5126f7a9753c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.drop_index('ix_user_lastname', table_name='user')
    op.drop_index('ix_user_surname', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('user', sa.Column('lastname', mysql.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_surname', 'user', ['surname'], unique=False)
    op.create_index('ix_user_lastname', 'user', ['lastname'], unique=False)
    op.drop_column('user', 'email')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
