"""empty message

Revision ID: 822abcf99160
Revises: 0b1f665c5991
Create Date: 2023-03-20 17:09:39.298379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822abcf99160'
down_revision = '0b1f665c5991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.Column('role_description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role')
    op.drop_table('roles')
    # ### end Alembic commands ###
