"""empty message

Revision ID: 90c66e8bff2d
Revises: d31836287d4a
Create Date: 2023-03-17 18:15:30.715849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90c66e8bff2d'
down_revision = 'd31836287d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bestellung', sa.Column('articles', sa.String(length=500), nullable=True))
    op.drop_column('bestellung', 'article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bestellung', sa.Column('article', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('bestellung', 'articles')
    # ### end Alembic commands ###
