"""empty message

Revision ID: 994e7c4055f8
Revises: 3542caa0fb4d
Create Date: 2023-03-20 12:37:01.330845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '994e7c4055f8'
down_revision = '3542caa0fb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bestellung', 'articles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bestellung', sa.Column('articles', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
