"""empty message

Revision ID: acca6c0a72dc
Revises: 5ef9a24e4927
Create Date: 2023-03-26 11:38:11.555663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acca6c0a72dc'
down_revision = '5ef9a24e4927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bestellung', 'orderDate')
    op.drop_column('bestellung', 'pickUpDate')
    op.drop_column('bestellung', 'returnDate')
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', mysql.VARCHAR(length=32), nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)
    op.add_column('bestellung', sa.Column('returnDate', mysql.DATETIME(), nullable=True))
    op.add_column('bestellung', sa.Column('pickUpDate', mysql.DATETIME(), nullable=True))
    op.add_column('bestellung', sa.Column('orderDate', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
