"""empty message

Revision ID: b399651c0c58
Revises: 90c66e8bff2d
Create Date: 2023-03-17 18:16:07.074347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b399651c0c58'
down_revision = '90c66e8bff2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bestellung', 'amount')
    op.drop_column('bestellung', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bestellung', sa.Column('description', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('bestellung', sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
