"""empty message

Revision ID: d31836287d4a
Revises: e6bc5179d750
Create Date: 2023-03-15 23:34:23.877067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31836287d4a'
down_revision = 'e6bc5179d750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bestellung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scoutname', sa.Integer(), nullable=True),
    sa.Column('orderDate', sa.DateTime(), nullable=True),
    sa.Column('activityDate', sa.DateTime(), nullable=True),
    sa.Column('pickUpDate', sa.DateTime(), nullable=True),
    sa.Column('returnDate', sa.DateTime(), nullable=True),
    sa.Column('article', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['scoutname'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bestellung')
    # ### end Alembic commands ###
