"""empty message

Revision ID: f937e108fb00
Revises: 994e7c4055f8
Create Date: 2023-03-20 14:03:51.806606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f937e108fb00'
down_revision = '994e7c4055f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bestellung', sa.Column('orderStatus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bestellung', 'orderStatus')
    # ### end Alembic commands ###
